import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface AdmissionLetterData {
  applicantName: string;
  programName: string;
  applicationId: number;
  reviewNote?: string | null;
}

const PRIMARY = rgb(0.12, 0.25, 0.46);
const MUTED = rgb(0.4, 0.4, 0.4);
const BLACK = rgb(0.1, 0.1, 0.1);

/**
 * Generate a one-page PDF admission letter and return the raw bytes.
 */
export async function generateAdmissionLetter(
  data: AdmissionLetterData,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4 portrait
  const { width, height } = page.getSize();

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontItalic = await doc.embedFont(StandardFonts.HelveticaOblique);

  const margin = 56;
  let y = height - margin;

  // Header band
  page.drawRectangle({
    x: 0,
    y: height - 110,
    width,
    height: 110,
    color: PRIMARY,
  });
  page.drawText("CENTRAL GLOBAL UNIVERSITY", {
    x: margin,
    y: height - 60,
    size: 22,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("Office of Admissions", {
    x: margin,
    y: height - 84,
    size: 12,
    font,
    color: rgb(0.85, 0.89, 0.96),
  });

  y = height - 150;

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  page.drawText(`Date: ${today}`, {
    x: margin,
    y,
    size: 10,
    font,
    color: MUTED,
  });
  page.drawText(`Reference: ADM-${data.applicationId}`, {
    x: width - margin - 140,
    y,
    size: 10,
    font,
    color: MUTED,
  });

  y -= 40;
  page.drawText("LETTER OF ADMISSION", {
    x: margin,
    y,
    size: 16,
    font: fontBold,
    color: PRIMARY,
  });

  y -= 36;
  page.drawText(`Dear ${data.applicantName},`, {
    x: margin,
    y,
    size: 12,
    font,
    color: BLACK,
  });

  const paragraphs = [
    `Congratulations! On behalf of Central Global University, it is our great pleasure to offer you admission into the ${data.programName} programme.`,
    `Your application has been carefully reviewed by our admissions committee, and we were impressed by your academic background and potential. We are confident that you will make valuable contributions to our academic community.`,
    `This offer of admission is formal confirmation of your acceptance. Further details regarding enrollment, orientation, and fee payment will be communicated to you through your student portal.`,
    `We look forward to welcoming you to Central Global University and wish you every success in your academic journey with us.`,
  ];

  y -= 28;
  const maxWidth = width - margin * 2;
  for (const para of paragraphs) {
    y = drawWrapped(page, para, {
      x: margin,
      y,
      size: 11,
      font,
      color: BLACK,
      maxWidth,
      lineHeight: 16,
    });
    y -= 14;
  }

  if (data.reviewNote) {
    y = drawWrapped(page, `Note from the admissions office: ${data.reviewNote}`, {
      x: margin,
      y,
      size: 10,
      font: fontItalic,
      color: MUTED,
      maxWidth,
      lineHeight: 14,
    });
    y -= 14;
  }

  y -= 24;
  page.drawText("Warm regards,", { x: margin, y, size: 11, font, color: BLACK });
  y -= 36;
  page.drawText("Registrar", { x: margin, y, size: 12, font: fontBold, color: PRIMARY });
  y -= 16;
  page.drawText("Office of Admissions, Central Global University", {
    x: margin,
    y,
    size: 10,
    font,
    color: MUTED,
  });

  // Footer
  page.drawLine({
    start: { x: margin, y: 70 },
    end: { x: width - margin, y: 70 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });
  page.drawText(
    "This is an official document generated by Central Global University.",
    { x: margin, y: 54, size: 8, font, color: MUTED },
  );

  return doc.save();
}

function drawWrapped(
  page: ReturnType<PDFDocument["addPage"]>,
  text: string,
  opts: {
    x: number;
    y: number;
    size: number;
    font: Awaited<ReturnType<PDFDocument["embedFont"]>>;
    color: ReturnType<typeof rgb>;
    maxWidth: number;
    lineHeight: number;
  },
): number {
  const words = text.split(/\s+/);
  let line = "";
  let y = opts.y;
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    const w = opts.font.widthOfTextAtSize(candidate, opts.size);
    if (w > opts.maxWidth && line) {
      page.drawText(line, {
        x: opts.x,
        y,
        size: opts.size,
        font: opts.font,
        color: opts.color,
      });
      y -= opts.lineHeight;
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) {
    page.drawText(line, {
      x: opts.x,
      y,
      size: opts.size,
      font: opts.font,
      color: opts.color,
    });
    y -= opts.lineHeight;
  }
  return y;
}
