import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface InvoiceData {
  invoiceNumber: string;
  studentName: string;
  studentEmail: string;
  courseTitle: string;
  amount: number;
  currency: string;
  status: string;
  provider: string;
  reference?: string | null;
  date: Date;
}

const PRIMARY = rgb(0.12, 0.25, 0.46);
const MUTED = rgb(0.4, 0.4, 0.4);
const BLACK = rgb(0.1, 0.1, 0.1);
const LINE = rgb(0.85, 0.85, 0.85);

/**
 * Generate a one-page PDF invoice / receipt and return the raw bytes.
 */
export async function generateInvoice(data: InvoiceData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4 portrait
  const { width, height } = page.getSize();

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const margin = 56;

  // Header band
  page.drawRectangle({ x: 0, y: height - 110, width, height: 110, color: PRIMARY });
  page.drawText("CENTRAL GLOBAL UNIVERSITY", {
    x: margin,
    y: height - 56,
    size: 20,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("Office of the Bursar", {
    x: margin,
    y: height - 80,
    size: 11,
    font,
    color: rgb(0.85, 0.89, 0.96),
  });
  page.drawText("INVOICE", {
    x: width - margin - 90,
    y: height - 62,
    size: 24,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  let y = height - 150;

  const fmtDate = data.date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Meta block (right aligned labels)
  const metaRows: [string, string][] = [
    ["Invoice No.", data.invoiceNumber],
    ["Date", fmtDate],
    ["Status", data.status.toUpperCase()],
  ];
  for (const [label, value] of metaRows) {
    page.drawText(label, { x: width - margin - 220, y, size: 10, font, color: MUTED });
    page.drawText(value, { x: width - margin - 110, y, size: 10, font: fontBold, color: BLACK });
    y -= 16;
  }

  // Bill to
  y = height - 150;
  page.drawText("BILL TO", { x: margin, y, size: 10, font: fontBold, color: MUTED });
  y -= 18;
  page.drawText(data.studentName, { x: margin, y, size: 12, font: fontBold, color: BLACK });
  y -= 16;
  page.drawText(data.studentEmail, { x: margin, y, size: 10, font, color: MUTED });

  // Table header
  y = height - 250;
  page.drawRectangle({ x: margin, y: y - 6, width: width - margin * 2, height: 26, color: rgb(0.95, 0.96, 0.98) });
  page.drawText("DESCRIPTION", { x: margin + 10, y, size: 10, font: fontBold, color: PRIMARY });
  page.drawText("AMOUNT", { x: width - margin - 90, y, size: 10, font: fontBold, color: PRIMARY });

  y -= 34;
  page.drawText(`Tuition — ${data.courseTitle}`, { x: margin + 10, y, size: 11, font, color: BLACK });
  page.drawText(`${data.currency} ${data.amount.toFixed(2)}`, {
    x: width - margin - 90,
    y,
    size: 11,
    font,
    color: BLACK,
  });

  y -= 18;
  page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 1, color: LINE });

  // Total
  y -= 28;
  page.drawText("TOTAL", { x: width - margin - 200, y, size: 12, font: fontBold, color: BLACK });
  page.drawText(`${data.currency} ${data.amount.toFixed(2)}`, {
    x: width - margin - 90,
    y,
    size: 12,
    font: fontBold,
    color: PRIMARY,
  });

  // Payment details
  y -= 60;
  page.drawText("PAYMENT DETAILS", { x: margin, y, size: 10, font: fontBold, color: MUTED });
  y -= 18;
  page.drawText(`Method: ${data.provider}`, { x: margin, y, size: 10, font, color: BLACK });
  if (data.reference) {
    y -= 14;
    page.drawText(`Transaction Reference: ${data.reference}`, { x: margin, y, size: 10, font, color: BLACK });
  }

  // Footer
  page.drawLine({
    start: { x: margin, y: 70 },
    end: { x: width - margin, y: 70 },
    thickness: 1,
    color: LINE,
  });
  page.drawText(
    "Thank you for your payment. This is an official receipt generated by Central Global University.",
    { x: margin, y: 54, size: 8, font, color: MUTED },
  );

  return doc.save();
}
