import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface ResultReportData {
  studentName: string;
  studentEmail: string;
  examTitle: string;
  subjectTitle: string;
  courseTitle: string;
  score: number;
  totalMarks: number;
  grade?: string | null;
  passed: boolean;
  remarks?: string | null;
  publishedAt: Date;
}

const PRIMARY = rgb(0.12, 0.25, 0.46);
const MUTED = rgb(0.4, 0.4, 0.4);
const BLACK = rgb(0.1, 0.1, 0.1);
const LINE = rgb(0.85, 0.85, 0.85);
const PASS = rgb(0.13, 0.5, 0.23);
const FAIL = rgb(0.7, 0.16, 0.16);

/**
 * Generate a one-page PDF result slip and return the raw bytes.
 */
export async function generateResultReport(
  data: ResultReportData,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4 portrait
  const { width, height } = page.getSize();

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const margin = 56;

  // Header band
  page.drawRectangle({ x: 0, y: height - 110, width, height: 110, color: PRIMARY });
  page.drawText("CENTRAL GLOBAL UNIVERSITY", {
    x: margin,
    y: height - 56,
    size: 20,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("Office of the Registrar", {
    x: margin,
    y: height - 80,
    size: 11,
    font,
    color: rgb(0.85, 0.89, 0.96),
  });
  page.drawText("RESULT SLIP", {
    x: width - margin - 130,
    y: height - 62,
    size: 22,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  // Meta block (right aligned)
  let y = height - 150;
  const fmtDate = data.publishedAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const metaRows: [string, string][] = [["Published", fmtDate]];
  for (const [label, value] of metaRows) {
    page.drawText(label, { x: width - margin - 220, y, size: 10, font, color: MUTED });
    page.drawText(value, { x: width - margin - 110, y, size: 10, font: fontBold, color: BLACK });
    y -= 16;
  }

  // Student block
  y = height - 150;
  page.drawText("STUDENT", { x: margin, y, size: 10, font: fontBold, color: MUTED });
  y -= 18;
  page.drawText(data.studentName, { x: margin, y, size: 12, font: fontBold, color: BLACK });
  y -= 16;
  page.drawText(data.studentEmail, { x: margin, y, size: 10, font, color: MUTED });

  // Course / subject
  y = height - 250;
  const infoRows: [string, string][] = [
    ["Course", data.courseTitle],
    ["Subject", data.subjectTitle],
    ["Examination", data.examTitle],
  ];
  for (const [label, value] of infoRows) {
    page.drawText(label, { x: margin, y, size: 10, font, color: MUTED });
    page.drawText(value, { x: margin + 110, y, size: 11, font: fontBold, color: BLACK });
    y -= 22;
  }

  // Score table
  y -= 10;
  page.drawRectangle({ x: margin, y: y - 6, width: width - margin * 2, height: 26, color: rgb(0.95, 0.96, 0.98) });
  page.drawText("ASSESSMENT", { x: margin + 10, y, size: 10, font: fontBold, color: PRIMARY });
  page.drawText("MARKS", { x: width - margin - 120, y, size: 10, font: fontBold, color: PRIMARY });

  y -= 34;
  page.drawText(data.examTitle, { x: margin + 10, y, size: 11, font, color: BLACK });
  page.drawText(`${data.score} / ${data.totalMarks}`, {
    x: width - margin - 120,
    y,
    size: 11,
    font,
    color: BLACK,
  });

  y -= 18;
  page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 1, color: LINE });

  // Grade + outcome
  y -= 30;
  page.drawText("Grade", { x: margin, y, size: 11, font, color: MUTED });
  page.drawText(data.grade ?? "—", { x: margin + 110, y, size: 12, font: fontBold, color: BLACK });

  y -= 24;
  page.drawText("Outcome", { x: margin, y, size: 11, font, color: MUTED });
  page.drawText(data.passed ? "PASS" : "FAIL", {
    x: margin + 110,
    y,
    size: 13,
    font: fontBold,
    color: data.passed ? PASS : FAIL,
  });

  if (data.remarks) {
    y -= 36;
    page.drawText("REMARKS", { x: margin, y, size: 10, font: fontBold, color: MUTED });
    y -= 16;
    const remarks = data.remarks.slice(0, 400);
    page.drawText(remarks, { x: margin, y, size: 10, font, color: BLACK, maxWidth: width - margin * 2, lineHeight: 14 });
  }

  // Footer
  page.drawLine({
    start: { x: margin, y: 70 },
    end: { x: width - margin, y: 70 },
    thickness: 1,
    color: LINE,
  });
  page.drawText(
    "This is an official result slip generated by Central Global University.",
    { x: margin, y: 54, size: 8, font, color: MUTED },
  );

  return doc.save();
}
